### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by CatsMum** [leaningtech/cheerp-meta#35]
Using gcc 6.2.1
output is:

[  4%] Building CXX object lib/TableGen/CMakeFiles/LLVMTableGen.dir/Main.cpp.o
In file included from /usr/include/c++/6.2.1/bits/concept_check.h:56:0,
                 from /usr/include/c++/6.2.1/bits/move.h:34,
                 from /usr/include/c++/6.2.1/bits/stl_pair.h:59,
                 from /usr/include/c++/6.2.1/utility:70,
                 from /usr/include/c++/6.2.1/algorithm:60,
                 from /home/nicole/software/cheerp/cheerp-llvm/include/llvm/ADT/StringRef.h:13,
                 from /home/nicole/software/cheerp/cheerp-llvm/lib/TableGen/TGLexer.h:17,
                 from /home/nicole/software/cheerp/cheerp-llvm/lib/TableGen/TGParser.h:17,
                 from /home/nicole/software/cheerp/cheerp-llvm/lib/TableGen/Main.cpp:18:
/usr/include/c++/6.2.1/bits/boost_concept_check.h: In instantiation of ‘void __gnu_cxx::_SGIAssignableConcept<_Tp>::__constraints() [with _Tp = std::unique_ptr<llvm::Record>]’:
/usr/include/c++/6.2.1/bits/stl_map.h:108:7:   required from ‘class std::map<std::__cxx11::basic_string<char>, std::unique_ptr<llvm::Record> >’
/home/nicole/software/cheerp/cheerp-llvm/include/llvm/TableGen/Record.h:1677:13:   required from here
/usr/include/c++/6.2.1/bits/boost_concept_check.h:205:28: error: use of deleted function ‘std::unique_ptr<_Tp, _Dp>::unique_ptr(const std::unique_ptr<_Tp, _Dp>&) [with _Tp = llvm::Record; _Dp = std::default_delete<llvm::Record>]’
       _Tp __b _IsUnused(__a);
                            ^
In file included from /usr/include/c++/6.2.1/memory:81:0,
                 from /home/nicole/software/cheerp/cheerp-llvm/include/llvm/ADT/STLExtras.h:25,
                 from /home/nicole/software/cheerp/cheerp-llvm/include/llvm/ADT/ArrayRef.h:14,
                 from /home/nicole/software/cheerp/cheerp-llvm/include/llvm/Support/SourceMgr.h:19,
                 from /home/nicole/software/cheerp/cheerp-llvm/lib/TableGen/TGParser.h:19,
                 from /home/nicole/software/cheerp/cheerp-llvm/lib/TableGen/Main.cpp:18:
/usr/include/c++/6.2.1/bits/unique_ptr.h:356:7: note: declared here
       unique_ptr(const unique_ptr&) = delete;
       ^~~~~~~~~~
In file included from /usr/include/c++/6.2.1/bits/concept_check.h:56:0,
                 from /usr/include/c++/6.2.1/bits/move.h:34,
                 from /usr/include/c++/6.2.1/bits/stl_pair.h:59,
                 from /usr/include/c++/6.2.1/utility:70,
                 from /usr/include/c++/6.2.1/algorithm:60,
                 from /home/nicole/software/cheerp/cheerp-llvm/include/llvm/ADT/StringRef.h:13,
                 from /home/nicole/software/cheerp/cheerp-llvm/lib/TableGen/TGLexer.h:17,
                 from /home/nicole/software/cheerp/cheerp-llvm/lib/TableGen/TGParser.h:17,
                 from /home/nicole/software/cheerp/cheerp-llvm/lib/TableGen/Main.cpp:18:
/usr/include/c++/6.2.1/bits/boost_concept_check.h:206:11: error: use of deleted function ‘std::unique_ptr<_Tp, _Dp>& std::unique_ptr<_Tp, _Dp>::operator=(const std::unique_ptr<_Tp, _Dp>&) [with _Tp = llvm::Record; _Dp = std::default_delete<llvm::Record>]’
       __a = __a;                        // require assignment operator
       ~~~~^~~~~
In file included from /usr/include/c++/6.2.1/memory:81:0,
                 from /home/nicole/software/cheerp/cheerp-llvm/include/llvm/ADT/STLExtras.h:25,
                 from /home/nicole/software/cheerp/cheerp-llvm/include/llvm/ADT/ArrayRef.h:14,
                 from /home/nicole/software/cheerp/cheerp-llvm/include/llvm/Support/SourceMgr.h:19,
                 from /home/nicole/software/cheerp/cheerp-llvm/lib/TableGen/TGParser.h:19,
                 from /home/nicole/software/cheerp/cheerp-llvm/lib/TableGen/Main.cpp:18:
/usr/include/c++/6.2.1/bits/unique_ptr.h:357:19: note: declared here
       unique_ptr& operator=(const unique_ptr&) = delete;
                   ^~~~~~~~
In file included from /usr/include/c++/6.2.1/bits/concept_check.h:56:0,
                 from /usr/include/c++/6.2.1/bits/move.h:34,
                 from /usr/include/c++/6.2.1/bits/stl_pair.h:59,
                 from /usr/include/c++/6.2.1/utility:70,
                 from /usr/include/c++/6.2.1/algorithm:60,
                 from /home/nicole/software/cheerp/cheerp-llvm/include/llvm/ADT/StringRef.h:13,
                 from /home/nicole/software/cheerp/cheerp-llvm/lib/TableGen/TGLexer.h:17,
                 from /home/nicole/software/cheerp/cheerp-llvm/lib/TableGen/TGParser.h:17,
                 from /home/nicole/software/cheerp/cheerp-llvm/lib/TableGen/Main.cpp:18:
/usr/include/c++/6.2.1/bits/boost_concept_check.h: In instantiation of ‘void __gnu_cxx::_SGIAssignableConcept<_Tp>::__constraints() [with _Tp = std::unique_ptr<llvm::MultiClass>]’:
/usr/include/c++/6.2.1/bits/stl_map.h:108:7:   required from ‘class std::map<std::__cxx11::basic_string<char>, std::unique_ptr<llvm::MultiClass> >’
/home/nicole/software/cheerp/cheerp-llvm/lib/TableGen/TGParser.h:58:54:   required from here
/usr/include/c++/6.2.1/bits/boost_concept_check.h:205:28: error: use of deleted function ‘std::unique_ptr<_Tp, _Dp>::unique_ptr(const std::unique_ptr<_Tp, _Dp>&) [with _Tp = llvm::MultiClass; _Dp = std::default_delete<llvm::MultiClass>]’
       _Tp __b _IsUnused(__a);
                            ^
In file included from /usr/include/c++/6.2.1/memory:81:0,
                 from /home/nicole/software/cheerp/cheerp-llvm/include/llvm/ADT/STLExtras.h:25,
                 from /home/nicole/software/cheerp/cheerp-llvm/include/llvm/ADT/ArrayRef.h:14,
                 from /home/nicole/software/cheerp/cheerp-llvm/include/llvm/Support/SourceMgr.h:19,
                 from /home/nicole/software/cheerp/cheerp-llvm/lib/TableGen/TGParser.h:19,
                 from /home/nicole/software/cheerp/cheerp-llvm/lib/TableGen/Main.cpp:18:
/usr/include/c++/6.2.1/bits/unique_ptr.h:356:7: note: declared here
       unique_ptr(const unique_ptr&) = delete;
       ^~~~~~~~~~
In file included from /usr/include/c++/6.2.1/bits/concept_check.h:56:0,
                 from /usr/include/c++/6.2.1/bits/move.h:34,
                 from /usr/include/c++/6.2.1/bits/stl_pair.h:59,
                 from /usr/include/c++/6.2.1/utility:70,
                 from /usr/include/c++/6.2.1/algorithm:60,
                 from /home/nicole/software/cheerp/cheerp-llvm/include/llvm/ADT/StringRef.h:13,
                 from /home/nicole/software/cheerp/cheerp-llvm/lib/TableGen/TGLexer.h:17,
                 from /home/nicole/software/cheerp/cheerp-llvm/lib/TableGen/TGParser.h:17,
                 from /home/nicole/software/cheerp/cheerp-llvm/lib/TableGen/Main.cpp:18:
/usr/include/c++/6.2.1/bits/boost_concept_check.h:206:11: error: use of deleted function ‘std::unique_ptr<_Tp, _Dp>& std::unique_ptr<_Tp, _Dp>::operator=(const std::unique_ptr<_Tp, _Dp>&) [with _Tp = llvm::MultiClass; _Dp = std::default_delete<llvm::MultiClass>]’
       __a = __a;                        // require assignment operator
       ~~~~^~~~~
In file included from /usr/include/c++/6.2.1/memory:81:0,
                 from /home/nicole/software/cheerp/cheerp-llvm/include/llvm/ADT/STLExtras.h:25,
                 from /home/nicole/software/cheerp/cheerp-llvm/include/llvm/ADT/ArrayRef.h:14,
                 from /home/nicole/software/cheerp/cheerp-llvm/include/llvm/Support/SourceMgr.h:19,
                 from /home/nicole/software/cheerp/cheerp-llvm/lib/TableGen/TGParser.h:19,
                 from /home/nicole/software/cheerp/cheerp-llvm/lib/TableGen/Main.cpp:18:
/usr/include/c++/6.2.1/bits/unique_ptr.h:357:19: note: declared here
       unique_ptr& operator=(const unique_ptr&) = delete;
                   ^~~~~~~~
make[2]: *** [lib/TableGen/CMakeFiles/LLVMTableGen.dir/build.make:87: lib/TableGen/CMakeFiles/LLVMTableGen.dir/Main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:222: lib/TableGen/CMakeFiles/LLVMTableGen.dir/all] Error 2
make: *** [Makefile:150: all] Error 2

**Comment by alexp-sssup** [comment]
It works fine with ```gcc version 6.2.0 20160901 (Ubuntu 6.2.0-3ubuntu11~16.04)```. The 6.2.1 build is very recent and there could still be issues. It is also possible there is a real problem in the LLVM code on which Cheerp is based, in which case it will probably be solved when we rebase Cheerp on a newer release of LLVM.

**Comment by CatsMum** [comment]
Che gioa! The wonders of Arch Linux - never a dull moment!
